name: Publish Quarto Slides
on:
  push:
    branches: main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render slides
        run: quarto render Synthetic-biology.qmd
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
